### ISSUE TITLE
Import export error

### ISSUE THREAD

**Issue by NN77296** [davidejones/alternativa3d_tools#3]
when trying to import a file on v1.20 and v1.19 i get this error. (i remember it was working before.)

Traceback (most recent call last): File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_alternativa3d_tools.py", line 2778, in execute A3DImport1(file,Config) File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_alternativa3d_tools.py", line 2801, in A3DImport1 a3d.read(file,a3dnull._mask) File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_alternativa3d_tools.py", line 3532, in read cla.read(file,mask,mskindex) File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_alternativa3d_tools.py", line 3912, in read print("name="+self._name) TypeError: Can't convert 'int' object to str implicitly location: <unknown location>:-1

And am i using the correct version of blender? (i tried the experimental nightly build from July 2019, and 2.79b)

**Comment by davidejones** [comment]
👋 Hey @NN77296, i'm a little suprised someone is using this project! I'd be curious to know what for

According to the code https://github.com/davidejones/alternativa3d_tools/blob/master/io_alternativa3d_tools.py#L5 I believe I was using blender 2.6.3 or greater at the time

Try the version here https://download.blender.org/release/Blender2.63/

**Comment by NN77296** [comment]
well, someone uploaded an EXE of the old Tanki 2.0 demos, and its on google drive. It works, and I've used your plugin a few years ago, and it was working just fine (_**i used it to view the models from the demo, but I didn't export them, I guess**_) I've tried 2.6.3 (i opened the script in a text editor and found the native version) but it still does this. what's weird is I opened the models in alternativa editor (as a3d) and exported as a3d, and it works...

**Comment by NN77296** [comment]
oh yeah, and speaking of the 2.0 demo, I've wasted so much time looking through internet archive and all the small overlooked places on the web looking for models and images and I haven't found anything XD (other than the demos)

**Comment by NN77296** [comment]
sorry i never got your message, my gmail is really weird and unsynced. I
was typing a message and realized i can upload them to mediafire for you.

https://www.mediafire.com/file/6rlzw2k3pmcl9n2/tanks.zip/file

**Comment by davidejones** [comment]
Sorry I took a while to come back to this, i just downloaded the files and tried running them through the importer. The int to str error is a simple bug but beyond that i noticed it still had issues importing.

Its an A3D version 1 file and for these files it tries to import by converting a3d1 files to a3d2. It looks like somewhere in there its incrementing objects incorrectly. I'll try dig in a bit further and see if i can find a fix.

**Comment by davidejones** [comment]
@NN77296 try using the changed script in this pr i made #4 and let me know what you think.

**Comment by NN77296** [comment]
im so sorry i didnt respond, why am i just now getting the email??

**Comment by davidejones** [comment]
No worries, I figured you would come back to this at some point 👍.

**Comment by NN77296** [comment]
Yeah I keep getting busy- I'm in middle school and when I'm just about to start doing stuff with this something comes to make me forget .-.

**Comment by NN77296** [comment]
> @NN77296 try using the changed script in this pr i made #4 and let me know what you think.

well, i just remembered today.
Finally i tried it, and yes it works!
school is... stressful...

**Comment by davidejones** [comment]
Great, thanks for testing again I appreciate it. I've merged those changes in, hope its useful for you and that school is less stressful!
